name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hoge: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - name: IP
        run: curl icanhazip.com
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run go vet
        run: go vet ./...
      - name: Run go build
        run: go build ./...
      - name: Run go test
        run: go test ./... -v -race
      - name: Prepare data
        run: cp .ci/terraform.tfvars examples/terraform/
      - name: Get terraform version
        working-directory: examples/terraform
        id: terraform-version
        run: echo "name=version::$(cat .terraform-version)" > ${GITHUB_OUTPUT}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.version }}
          terraform_wrapper: false
      - name: E2E test
        if: github.event.pull_request.head.repo.fork == false
        working-directory: examples/terraform
        run: make test
        env:
          CODECOV_API_V2_TOKEN: ${{ secrets.CODECOV_API_V2_TOKEN }}
