name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Run go vet
        run: go vet ./...
      - name: Run go build
        run: go build ./...
      - name: Run go test
        run: go test ./... -v -race
      - name: Install tfenv
        run: |
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "::add-path::$HOME/.tfenv/bin"
      - name: Prepare data
        run: |
          go build .
          dir=examples/terraform/.terraform/plugins/registry.terraform.io/at-wat/ucodecov/0.0.99/linux_amd64
          mkdir -p ${dir}
          cp terraform-provider-ucodecov ${dir}/terraform-provider-ucodecov_v0.0.99
          cp .ci/terraform.tfvars examples/terraform/
      - name: Install terraform
        working-directory: examples/terraform
        run: tfenv install
      - name: E2E test
        working-directory: examples/terraform
        run: |
          terraform init
          terraform plan
          terraform apply
        env:
          CODECOV_API_TOKEN: ${{ secrets.CODECOV_API_TOKEN }}
