name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run go vet
        run: go vet ./...
      - name: Run go build
        run: go build ./...
      - name: Run go test
        run: go test ./... -v -race
      - name: Prepare data
        run: |
          go build .
          dir=examples/terraform/.terraform/plugins/registry.terraform.io/at-wat/ucodecov/99.0.0/linux_amd64
          mkdir -p ${dir}
          cp terraform-provider-ucodecov ${dir}/terraform-provider-ucodecov_v99.0.0
          cp .ci/terraform.tfvars examples/terraform/
      - name: Get terraform version
        working-directory: examples/terraform
        id: terraform-version
        run: echo "name=version::$(cat .terraform-version)" > ${GITHUB_OUTPUT}
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.version }}
          terraform_wrapper: false
      - name: E2E test init
        working-directory: examples/terraform
        run: terraform init
      - name: E2E test plan
        if: github.event.pull_request.head.repo.fork == false
        working-directory: examples/terraform
        run: |
          terraform plan --out plan
          terraform apply -refresh=false plan
        env:
          CODECOV_API_V2_TOKEN: ${{ secrets.CODECOV_API_V2_TOKEN }}
